name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}

jobs:
    notify_start:
        runs-on: ubuntu-latest
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              if: env.SLACK_BOT_TOKEN != ''
              with:
                  channel: company-andculture-code-ci
                  color: "#3278BD"
                  status: STARTED

    build:
        runs-on: windows-latest
        needs: [notify_start]
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.5

            - name: nuget restore
              run: nuget restore All.sln

            - name: msbuild
              run: msbuild All.sln

    notify_success:
        runs-on: ubuntu-latest
        needs: [build]
        if: success()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              if: env.SLACK_BOT_TOKEN != ''
              with:
                  channel: company-andculture-code-ci
                  color: good
                  status: SUCCESS

    notify_failure:
        runs-on: ubuntu-latest
        needs: [build]
        if: failure()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              if: env.SLACK_BOT_TOKEN != ''
              with:
                  channel: company-andculture-code-ci
                  color: danger
                  status: FAILED